{{- if .Values.telegram.botToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "telectl.fullname" . }}
  labels:
    {{- include "telectl.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: {{ .Values.telegram.botToken | quote }}
  {{- if .Values.telegram.allowedUserIds }}
  ALLOWED_USER_IDS: {{ .Values.telegram.allowedUserIds | join "," | quote }}
  {{- end }}
  {{- if .Values.telegram.adminUserIds }}
  ADMIN_USER_IDS: {{ .Values.telegram.adminUserIds | join "," | quote }}
  {{- end }}
{{- end }}
